/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AgreementsRouteImport } from './routes/agreements'
import { Route as AtlasRouteImport } from './routes/atlas'
import { Route as BotRouteImport } from './routes/bot'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as CaseStudyRouteImport } from './routes/case-study'
import { Route as DoorsRouteImport } from './routes/doors'
import { Route as EventsRouteImport } from './routes/events'
import { Route as FoundRouteImport } from './routes/found'
import { Route as FundingRouteImport } from './routes/funding'
import { Route as HallRouteImport } from './routes/hall'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as LeadersRouteImport } from './routes/leaders'
import { Route as LettersRouteImport } from './routes/letters'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MeetRouteImport } from './routes/meet'
import { Route as MemberRouteImport } from './routes/member'
import { Route as MembersRouteImport } from './routes/members'
import { Route as MostSavedRouteImport } from './routes/most-saved'
import { Route as NewslettersRouteImport } from './routes/newsletters'
import { Route as OngoingRouteImport } from './routes/ongoing'
import { Route as PlusRouteImport } from './routes/plus'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as ReferRouteImport } from './routes/refer'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ResidenciesRouteImport } from './routes/residencies'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as SearchRouteImport } from './routes/search'
import { Route as TravelPlanRouteImport } from './routes/travel-plan'
import { Route as VennRouteImport } from './routes/venn'
import { Route as VisitsRouteImport } from './routes/visits'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as WorkStayRouteImport } from './routes/work-stay'
import { Route as ApiEmailLoginRouteImport } from './routes/api/email-login'
import { Route as ApiMeRouteImport } from './routes/api/me'
import { Route as ApiPasswordResetRouteImport } from './routes/api/password-reset'
import { Route as ApiRtcRouteImport } from './routes/api/rtc'
import { Route as CaravansRoomIdRouteImport } from './routes/caravans/$roomId'
import { Route as CharterIndexRouteImport } from './routes/charter/index'
import { Route as CharterFormIdRouteImport } from './routes/charter/$formId'
import { Route as CommunitiesSlugRouteImport } from './routes/communities/$slug'
import { Route as CompactsIndexRouteImport } from './routes/compacts/index'
import { Route as CompactsKindIdRouteImport } from './routes/compacts/$kindId'
import { Route as PeopleUserIdRouteImport } from './routes/people/$userId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as CommunitiesSlugDoorsRouteImport } from './routes/communities_.$slug.doors'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AgreementsRoute = AgreementsRouteImport.update({
  id: '/agreements',
  path: '/agreements',
  getParentRoute: () => rootRouteImport,
} as any)
const AtlasRoute = AtlasRouteImport.update({
  id: '/atlas',
  path: '/atlas',
  getParentRoute: () => rootRouteImport,
} as any)
const BotRoute = BotRouteImport.update({
  id: '/bot',
  path: '/bot',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudyRoute = CaseStudyRouteImport.update({
  id: '/case-study',
  path: '/case-study',
  getParentRoute: () => rootRouteImport,
} as any)
const DoorsRoute = DoorsRouteImport.update({
  id: '/doors',
  path: '/doors',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const FoundRoute = FoundRouteImport.update({
  id: '/found',
  path: '/found',
  getParentRoute: () => rootRouteImport,
} as any)
const FundingRoute = FundingRouteImport.update({
  id: '/funding',
  path: '/funding',
  getParentRoute: () => rootRouteImport,
} as any)
const HallRoute = HallRouteImport.update({
  id: '/hall',
  path: '/hall',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadersRoute = LeadersRouteImport.update({
  id: '/leaders',
  path: '/leaders',
  getParentRoute: () => rootRouteImport,
} as any)
const LettersRoute = LettersRouteImport.update({
  id: '/letters',
  path: '/letters',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetRoute = MeetRouteImport.update({
  id: '/meet',
  path: '/meet',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberRoute = MemberRouteImport.update({
  id: '/member',
  path: '/member',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersRoute = MembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => rootRouteImport,
} as any)
const MostSavedRoute = MostSavedRouteImport.update({
  id: '/most-saved',
  path: '/most-saved',
  getParentRoute: () => rootRouteImport,
} as any)
const NewslettersRoute = NewslettersRouteImport.update({
  id: '/newsletters',
  path: '/newsletters',
  getParentRoute: () => rootRouteImport,
} as any)
const OngoingRoute = OngoingRouteImport.update({
  id: '/ongoing',
  path: '/ongoing',
  getParentRoute: () => rootRouteImport,
} as any)
const PlusRoute = PlusRouteImport.update({
  id: '/plus',
  path: '/plus',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferRoute = ReferRouteImport.update({
  id: '/refer',
  path: '/refer',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResidenciesRoute = ResidenciesRouteImport.update({
  id: '/residencies',
  path: '/residencies',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const TravelPlanRoute = TravelPlanRouteImport.update({
  id: '/travel-plan',
  path: '/travel-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const VennRoute = VennRouteImport.update({
  id: '/venn',
  path: '/venn',
  getParentRoute: () => rootRouteImport,
} as any)
const VisitsRoute = VisitsRouteImport.update({
  id: '/visits',
  path: '/visits',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkStayRoute = WorkStayRouteImport.update({
  id: '/work-stay',
  path: '/work-stay',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEmailLoginRoute = ApiEmailLoginRouteImport.update({
  id: '/api/email-login',
  path: '/api/email-login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMeRoute = ApiMeRouteImport.update({
  id: '/api/me',
  path: '/api/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPasswordResetRoute = ApiPasswordResetRouteImport.update({
  id: '/api/password-reset',
  path: '/api/password-reset',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRtcRoute = ApiRtcRouteImport.update({
  id: '/api/rtc',
  path: '/api/rtc',
  getParentRoute: () => rootRouteImport,
} as any)
const CaravansRoomIdRoute = CaravansRoomIdRouteImport.update({
  id: '/caravans/$roomId',
  path: '/caravans/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)
const CharterIndexRoute = CharterIndexRouteImport.update({
  id: '/charter/',
  path: '/charter/',
  getParentRoute: () => rootRouteImport,
} as any)
const CharterFormIdRoute = CharterFormIdRouteImport.update({
  id: '/charter/$formId',
  path: '/charter/$formId',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunitiesSlugRoute = CommunitiesSlugRouteImport.update({
  id: '/communities/$slug',
  path: '/communities/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CompactsIndexRoute = CompactsIndexRouteImport.update({
  id: '/compacts/',
  path: '/compacts/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompactsKindIdRoute = CompactsKindIdRouteImport.update({
  id: '/compacts/$kindId',
  path: '/compacts/$kindId',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleUserIdRoute = PeopleUserIdRouteImport.update({
  id: '/people/$userId',
  path: '/people/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunitiesSlugDoorsRoute = CommunitiesSlugDoorsRouteImport.update({
  id: '/communities_/$slug/doors',
  path: '/communities/$slug/doors',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/agreements': typeof AgreementsRoute
  '/atlas': typeof AtlasRoute
  '/bot': typeof BotRoute
  '/calendar': typeof CalendarRoute
  '/case-study': typeof CaseStudyRoute
  '/doors': typeof DoorsRoute
  '/events': typeof EventsRoute
  '/found': typeof FoundRoute
  '/funding': typeof FundingRoute
  '/hall': typeof HallRoute
  '/leaderboard': typeof LeaderboardRoute
  '/leaders': typeof LeadersRoute
  '/letters': typeof LettersRoute
  '/login': typeof LoginRoute
  '/meet': typeof MeetRoute
  '/member': typeof MemberRoute
  '/members': typeof MembersRoute
  '/most-saved': typeof MostSavedRoute
  '/newsletters': typeof NewslettersRoute
  '/ongoing': typeof OngoingRoute
  '/plus': typeof PlusRoute
  '/profile': typeof ProfileRoute
  '/quiz': typeof QuizRoute
  '/refer': typeof ReferRoute
  '/reset-password': typeof ResetPasswordRoute
  '/residencies': typeof ResidenciesRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/travel-plan': typeof TravelPlanRoute
  '/venn': typeof VennRoute
  '/visits': typeof VisitsRoute
  '/welcome': typeof WelcomeRoute
  '/work-stay': typeof WorkStayRoute
  '/api/email-login': typeof ApiEmailLoginRoute
  '/api/me': typeof ApiMeRoute
  '/api/password-reset': typeof ApiPasswordResetRoute
  '/api/rtc': typeof ApiRtcRoute
  '/caravans/$roomId': typeof CaravansRoomIdRoute
  '/charter/$formId': typeof CharterFormIdRoute
  '/communities/$slug': typeof CommunitiesSlugRoute
  '/compacts/$kindId': typeof CompactsKindIdRoute
  '/people/$userId': typeof PeopleUserIdRoute
  '/charter/': typeof CharterIndexRoute
  '/compacts/': typeof CompactsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/communities/$slug/doors': typeof CommunitiesSlugDoorsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/agreements': typeof AgreementsRoute
  '/atlas': typeof AtlasRoute
  '/bot': typeof BotRoute
  '/calendar': typeof CalendarRoute
  '/case-study': typeof CaseStudyRoute
  '/doors': typeof DoorsRoute
  '/events': typeof EventsRoute
  '/found': typeof FoundRoute
  '/funding': typeof FundingRoute
  '/hall': typeof HallRoute
  '/leaderboard': typeof LeaderboardRoute
  '/leaders': typeof LeadersRoute
  '/letters': typeof LettersRoute
  '/login': typeof LoginRoute
  '/meet': typeof MeetRoute
  '/member': typeof MemberRoute
  '/members': typeof MembersRoute
  '/most-saved': typeof MostSavedRoute
  '/newsletters': typeof NewslettersRoute
  '/ongoing': typeof OngoingRoute
  '/plus': typeof PlusRoute
  '/profile': typeof ProfileRoute
  '/quiz': typeof QuizRoute
  '/refer': typeof ReferRoute
  '/reset-password': typeof ResetPasswordRoute
  '/residencies': typeof ResidenciesRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/travel-plan': typeof TravelPlanRoute
  '/venn': typeof VennRoute
  '/visits': typeof VisitsRoute
  '/welcome': typeof WelcomeRoute
  '/work-stay': typeof WorkStayRoute
  '/api/email-login': typeof ApiEmailLoginRoute
  '/api/me': typeof ApiMeRoute
  '/api/password-reset': typeof ApiPasswordResetRoute
  '/api/rtc': typeof ApiRtcRoute
  '/caravans/$roomId': typeof CaravansRoomIdRoute
  '/charter/$formId': typeof CharterFormIdRoute
  '/communities/$slug': typeof CommunitiesSlugRoute
  '/compacts/$kindId': typeof CompactsKindIdRoute
  '/people/$userId': typeof PeopleUserIdRoute
  '/charter': typeof CharterIndexRoute
  '/compacts': typeof CompactsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/communities/$slug/doors': typeof CommunitiesSlugDoorsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/agreements': typeof AgreementsRoute
  '/atlas': typeof AtlasRoute
  '/bot': typeof BotRoute
  '/calendar': typeof CalendarRoute
  '/case-study': typeof CaseStudyRoute
  '/doors': typeof DoorsRoute
  '/events': typeof EventsRoute
  '/found': typeof FoundRoute
  '/funding': typeof FundingRoute
  '/hall': typeof HallRoute
  '/leaderboard': typeof LeaderboardRoute
  '/leaders': typeof LeadersRoute
  '/letters': typeof LettersRoute
  '/login': typeof LoginRoute
  '/meet': typeof MeetRoute
  '/member': typeof MemberRoute
  '/members': typeof MembersRoute
  '/most-saved': typeof MostSavedRoute
  '/newsletters': typeof NewslettersRoute
  '/ongoing': typeof OngoingRoute
  '/plus': typeof PlusRoute
  '/profile': typeof ProfileRoute
  '/quiz': typeof QuizRoute
  '/refer': typeof ReferRoute
  '/reset-password': typeof ResetPasswordRoute
  '/residencies': typeof ResidenciesRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/travel-plan': typeof TravelPlanRoute
  '/venn': typeof VennRoute
  '/visits': typeof VisitsRoute
  '/welcome': typeof WelcomeRoute
  '/work-stay': typeof WorkStayRoute
  '/api/email-login': typeof ApiEmailLoginRoute
  '/api/me': typeof ApiMeRoute
  '/api/password-reset': typeof ApiPasswordResetRoute
  '/api/rtc': typeof ApiRtcRoute
  '/caravans/$roomId': typeof CaravansRoomIdRoute
  '/charter/$formId': typeof CharterFormIdRoute
  '/communities/$slug': typeof CommunitiesSlugRoute
  '/compacts/$kindId': typeof CompactsKindIdRoute
  '/people/$userId': typeof PeopleUserIdRoute
  '/charter/': typeof CharterIndexRoute
  '/compacts/': typeof CompactsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/communities_/$slug/doors': typeof CommunitiesSlugDoorsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/agreements'
    | '/atlas'
    | '/bot'
    | '/calendar'
    | '/case-study'
    | '/doors'
    | '/events'
    | '/found'
    | '/funding'
    | '/hall'
    | '/leaderboard'
    | '/leaders'
    | '/letters'
    | '/login'
    | '/meet'
    | '/member'
    | '/members'
    | '/most-saved'
    | '/newsletters'
    | '/ongoing'
    | '/plus'
    | '/profile'
    | '/quiz'
    | '/refer'
    | '/reset-password'
    | '/residencies'
    | '/saved'
    | '/search'
    | '/travel-plan'
    | '/venn'
    | '/visits'
    | '/welcome'
    | '/work-stay'
    | '/api/email-login'
    | '/api/me'
    | '/api/password-reset'
    | '/api/rtc'
    | '/caravans/$roomId'
    | '/charter/$formId'
    | '/communities/$slug'
    | '/compacts/$kindId'
    | '/people/$userId'
    | '/charter/'
    | '/compacts/'
    | '/api/auth/$'
    | '/communities/$slug/doors'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/agreements'
    | '/atlas'
    | '/bot'
    | '/calendar'
    | '/case-study'
    | '/doors'
    | '/events'
    | '/found'
    | '/funding'
    | '/hall'
    | '/leaderboard'
    | '/leaders'
    | '/letters'
    | '/login'
    | '/meet'
    | '/member'
    | '/members'
    | '/most-saved'
    | '/newsletters'
    | '/ongoing'
    | '/plus'
    | '/profile'
    | '/quiz'
    | '/refer'
    | '/reset-password'
    | '/residencies'
    | '/saved'
    | '/search'
    | '/travel-plan'
    | '/venn'
    | '/visits'
    | '/welcome'
    | '/work-stay'
    | '/api/email-login'
    | '/api/me'
    | '/api/password-reset'
    | '/api/rtc'
    | '/caravans/$roomId'
    | '/charter/$formId'
    | '/communities/$slug'
    | '/compacts/$kindId'
    | '/people/$userId'
    | '/charter'
    | '/compacts'
    | '/api/auth/$'
    | '/communities/$slug/doors'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/agreements'
    | '/atlas'
    | '/bot'
    | '/calendar'
    | '/case-study'
    | '/doors'
    | '/events'
    | '/found'
    | '/funding'
    | '/hall'
    | '/leaderboard'
    | '/leaders'
    | '/letters'
    | '/login'
    | '/meet'
    | '/member'
    | '/members'
    | '/most-saved'
    | '/newsletters'
    | '/ongoing'
    | '/plus'
    | '/profile'
    | '/quiz'
    | '/refer'
    | '/reset-password'
    | '/residencies'
    | '/saved'
    | '/search'
    | '/travel-plan'
    | '/venn'
    | '/visits'
    | '/welcome'
    | '/work-stay'
    | '/api/email-login'
    | '/api/me'
    | '/api/password-reset'
    | '/api/rtc'
    | '/caravans/$roomId'
    | '/charter/$formId'
    | '/communities/$slug'
    | '/compacts/$kindId'
    | '/people/$userId'
    | '/charter/'
    | '/compacts/'
    | '/api/auth/$'
    | '/communities_/$slug/doors'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AgreementsRoute: typeof AgreementsRoute
  AtlasRoute: typeof AtlasRoute
  BotRoute: typeof BotRoute
  CalendarRoute: typeof CalendarRoute
  CaseStudyRoute: typeof CaseStudyRoute
  DoorsRoute: typeof DoorsRoute
  EventsRoute: typeof EventsRoute
  FoundRoute: typeof FoundRoute
  FundingRoute: typeof FundingRoute
  HallRoute: typeof HallRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LeadersRoute: typeof LeadersRoute
  LettersRoute: typeof LettersRoute
  LoginRoute: typeof LoginRoute
  MeetRoute: typeof MeetRoute
  MemberRoute: typeof MemberRoute
  MembersRoute: typeof MembersRoute
  MostSavedRoute: typeof MostSavedRoute
  NewslettersRoute: typeof NewslettersRoute
  OngoingRoute: typeof OngoingRoute
  PlusRoute: typeof PlusRoute
  ProfileRoute: typeof ProfileRoute
  QuizRoute: typeof QuizRoute
  ReferRoute: typeof ReferRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ResidenciesRoute: typeof ResidenciesRoute
  SavedRoute: typeof SavedRoute
  SearchRoute: typeof SearchRoute
  TravelPlanRoute: typeof TravelPlanRoute
  VennRoute: typeof VennRoute
  VisitsRoute: typeof VisitsRoute
  WelcomeRoute: typeof WelcomeRoute
  WorkStayRoute: typeof WorkStayRoute
  ApiEmailLoginRoute: typeof ApiEmailLoginRoute
  ApiMeRoute: typeof ApiMeRoute
  ApiPasswordResetRoute: typeof ApiPasswordResetRoute
  ApiRtcRoute: typeof ApiRtcRoute
  CaravansRoomIdRoute: typeof CaravansRoomIdRoute
  CharterFormIdRoute: typeof CharterFormIdRoute
  CommunitiesSlugRoute: typeof CommunitiesSlugRoute
  CompactsKindIdRoute: typeof CompactsKindIdRoute
  PeopleUserIdRoute: typeof PeopleUserIdRoute
  CharterIndexRoute: typeof CharterIndexRoute
  CompactsIndexRoute: typeof CompactsIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  CommunitiesSlugDoorsRoute: typeof CommunitiesSlugDoorsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agreements': {
      id: '/agreements'
      path: '/agreements'
      fullPath: '/agreements'
      preLoaderRoute: typeof AgreementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atlas': {
      id: '/atlas'
      path: '/atlas'
      fullPath: '/atlas'
      preLoaderRoute: typeof AtlasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bot': {
      id: '/bot'
      path: '/bot'
      fullPath: '/bot'
      preLoaderRoute: typeof BotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-study': {
      id: '/case-study'
      path: '/case-study'
      fullPath: '/case-study'
      preLoaderRoute: typeof CaseStudyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doors': {
      id: '/doors'
      path: '/doors'
      fullPath: '/doors'
      preLoaderRoute: typeof DoorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/found': {
      id: '/found'
      path: '/found'
      fullPath: '/found'
      preLoaderRoute: typeof FoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funding': {
      id: '/funding'
      path: '/funding'
      fullPath: '/funding'
      preLoaderRoute: typeof FundingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hall': {
      id: '/hall'
      path: '/hall'
      fullPath: '/hall'
      preLoaderRoute: typeof HallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaders': {
      id: '/leaders'
      path: '/leaders'
      fullPath: '/leaders'
      preLoaderRoute: typeof LeadersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/letters': {
      id: '/letters'
      path: '/letters'
      fullPath: '/letters'
      preLoaderRoute: typeof LettersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meet': {
      id: '/meet'
      path: '/meet'
      fullPath: '/meet'
      preLoaderRoute: typeof MeetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/member': {
      id: '/member'
      path: '/member'
      fullPath: '/member'
      preLoaderRoute: typeof MemberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members': {
      id: '/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof MembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/most-saved': {
      id: '/most-saved'
      path: '/most-saved'
      fullPath: '/most-saved'
      preLoaderRoute: typeof MostSavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletters': {
      id: '/newsletters'
      path: '/newsletters'
      fullPath: '/newsletters'
      preLoaderRoute: typeof NewslettersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ongoing': {
      id: '/ongoing'
      path: '/ongoing'
      fullPath: '/ongoing'
      preLoaderRoute: typeof OngoingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plus': {
      id: '/plus'
      path: '/plus'
      fullPath: '/plus'
      preLoaderRoute: typeof PlusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refer': {
      id: '/refer'
      path: '/refer'
      fullPath: '/refer'
      preLoaderRoute: typeof ReferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/residencies': {
      id: '/residencies'
      path: '/residencies'
      fullPath: '/residencies'
      preLoaderRoute: typeof ResidenciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/travel-plan': {
      id: '/travel-plan'
      path: '/travel-plan'
      fullPath: '/travel-plan'
      preLoaderRoute: typeof TravelPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/venn': {
      id: '/venn'
      path: '/venn'
      fullPath: '/venn'
      preLoaderRoute: typeof VennRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visits': {
      id: '/visits'
      path: '/visits'
      fullPath: '/visits'
      preLoaderRoute: typeof VisitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work-stay': {
      id: '/work-stay'
      path: '/work-stay'
      fullPath: '/work-stay'
      preLoaderRoute: typeof WorkStayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/email-login': {
      id: '/api/email-login'
      path: '/api/email-login'
      fullPath: '/api/email-login'
      preLoaderRoute: typeof ApiEmailLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/me': {
      id: '/api/me'
      path: '/api/me'
      fullPath: '/api/me'
      preLoaderRoute: typeof ApiMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/password-reset': {
      id: '/api/password-reset'
      path: '/api/password-reset'
      fullPath: '/api/password-reset'
      preLoaderRoute: typeof ApiPasswordResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rtc': {
      id: '/api/rtc'
      path: '/api/rtc'
      fullPath: '/api/rtc'
      preLoaderRoute: typeof ApiRtcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caravans/$roomId': {
      id: '/caravans/$roomId'
      path: '/caravans/$roomId'
      fullPath: '/caravans/$roomId'
      preLoaderRoute: typeof CaravansRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/charter/': {
      id: '/charter/'
      path: '/charter'
      fullPath: '/charter/'
      preLoaderRoute: typeof CharterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/charter/$formId': {
      id: '/charter/$formId'
      path: '/charter/$formId'
      fullPath: '/charter/$formId'
      preLoaderRoute: typeof CharterFormIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communities/$slug': {
      id: '/communities/$slug'
      path: '/communities/$slug'
      fullPath: '/communities/$slug'
      preLoaderRoute: typeof CommunitiesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compacts/': {
      id: '/compacts/'
      path: '/compacts'
      fullPath: '/compacts/'
      preLoaderRoute: typeof CompactsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compacts/$kindId': {
      id: '/compacts/$kindId'
      path: '/compacts/$kindId'
      fullPath: '/compacts/$kindId'
      preLoaderRoute: typeof CompactsKindIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people/$userId': {
      id: '/people/$userId'
      path: '/people/$userId'
      fullPath: '/people/$userId'
      preLoaderRoute: typeof PeopleUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communities_/$slug/doors': {
      id: '/communities_/$slug/doors'
      path: '/communities/$slug/doors'
      fullPath: '/communities/$slug/doors'
      preLoaderRoute: typeof CommunitiesSlugDoorsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AgreementsRoute: AgreementsRoute,
  AtlasRoute: AtlasRoute,
  BotRoute: BotRoute,
  CalendarRoute: CalendarRoute,
  CaseStudyRoute: CaseStudyRoute,
  DoorsRoute: DoorsRoute,
  EventsRoute: EventsRoute,
  FoundRoute: FoundRoute,
  FundingRoute: FundingRoute,
  HallRoute: HallRoute,
  LeaderboardRoute: LeaderboardRoute,
  LeadersRoute: LeadersRoute,
  LettersRoute: LettersRoute,
  LoginRoute: LoginRoute,
  MeetRoute: MeetRoute,
  MemberRoute: MemberRoute,
  MembersRoute: MembersRoute,
  MostSavedRoute: MostSavedRoute,
  NewslettersRoute: NewslettersRoute,
  OngoingRoute: OngoingRoute,
  PlusRoute: PlusRoute,
  ProfileRoute: ProfileRoute,
  QuizRoute: QuizRoute,
  ReferRoute: ReferRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ResidenciesRoute: ResidenciesRoute,
  SavedRoute: SavedRoute,
  SearchRoute: SearchRoute,
  TravelPlanRoute: TravelPlanRoute,
  VennRoute: VennRoute,
  VisitsRoute: VisitsRoute,
  WelcomeRoute: WelcomeRoute,
  WorkStayRoute: WorkStayRoute,
  ApiEmailLoginRoute: ApiEmailLoginRoute,
  ApiMeRoute: ApiMeRoute,
  ApiPasswordResetRoute: ApiPasswordResetRoute,
  ApiRtcRoute: ApiRtcRoute,
  CaravansRoomIdRoute: CaravansRoomIdRoute,
  CharterFormIdRoute: CharterFormIdRoute,
  CommunitiesSlugRoute: CommunitiesSlugRoute,
  CompactsKindIdRoute: CompactsKindIdRoute,
  PeopleUserIdRoute: PeopleUserIdRoute,
  CharterIndexRoute: CharterIndexRoute,
  CompactsIndexRoute: CompactsIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  CommunitiesSlugDoorsRoute: CommunitiesSlugDoorsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
